version: "2.2"
services:
  #######################################
  # Web portal
  #######################################
  portal:
    image: "monachus/hugo:v0.48"
    volumes:
      - ${PWD}:/usr/share/blog
    ports:
      - "${PORT:-1313}:1313"
